### ISSUE TITLE
Invalid zone offsets added when none given

### ISSUE THREAD

**Issue by no-reply** [inukshuk/edtf-ruby#14]
Parsing a datetime with no zone offset results in a datetime with an offset of `+00:00`. 

```ruby
EDTF.parse("2001-02-03T09:30:01").edtf
# => "2001-02-03T09:30:01+00:00"
```

This introduces two problems: 

  - __ISO 8601 specifies that a zone designator is empty when making use of local time. The implementation encodes the time as UTC instead__.
  - The EDTF BNF grammar specifies that `00:00` is an invalid offset, allowing only for minutes `01`-`59` when the offset hour is `00`.  The relevant BNF is included below.  This may be a mistake in the BNF (it wouldn't be the only one). 8601 is silent on the matter, as far as I can tell.

I propose to omit the zone offset in the object representations & the `EDTF` output when none is given in the parsed string.

```
zoneOffset = "Z" 
      | ("+" | "-") 
                     (zoneOffsetHour (":" minute)?
                     | "14:00" 
                     | "00:" oneThru59 ) 

zoneOffsetHour = oneThru13
minute = zeroThru59

oneThru12 = "01" | "02" | "03" | "04" | "05" | "06" | "07" | "08" | "09" | "10" | "11" | "12"
oneThru13 = oneThru12 | "13"
oneThru23 = oneThru13 | "14" | "15" | "16" | "17" | "18" | "19" | "20" | "21" | "22" | "23"
zeroThru23 =  "00" | oneThru23
oneThru29 = oneThru23 | "24" | "25" | "26" | "27" | "28" | "29"
oneThru30 = oneThru29 | "30"
oneThru31 = oneThru30 | "31"
oneThru59 = oneThru31 | "32" | "33"| "34"| "35"| "36"| "37"| "38"| "39"| "40"| "41"| "42" | "43"
                | "44"| "45"| "46" | "47"| "48"| "49" |"50"|"51"|"52"|"53"|"54"|"55"|"56"|"57"|"58"|"59"
zeroThru59 = "00" | oneThru59 
```

**Comment by inukshuk** [comment]
I would like to stay as close as possible to Ruby's treatment of ISO 8601 -- if I am not mistaken this assumes UTC if no time zone is given:

     require 'time'
     DateTime.parse('2015-05-05T09:30:00').to_s
     => '2015-05-05T09:30:00+00:00'

So Ruby does not follow the 8601 suggestion here, it seems. But you are not proposing to change this directly, but rather to keep track of whether or not a time zone was present in the parsed string to be able to suppress it when printing, right?

The omission of +00:00 in the BNF is probably a mistake, it was there in a previous version I believe.

**Comment by inukshuk** [comment]
OK do you think this makes sense now:

    irb(main):001:0> EDTF.parse("2001-02-03T09:30:01").edtf
    => "2001-02-03T09:30:01"
    irb(main):002:0> EDTF.parse("2001-02-03T09:30:01+02:00").edtf
    => "2001-02-03T09:30:01+02:00"
    irb(main):003:0> EDTF.parse("2001-02-03T09:30:01+00:00").edtf
    => "2001-02-03T09:30:01+00:00"
    irb(main):004:0> EDTF.parse("2001-02-03T09:30:01Z").edtf
    => "2001-02-03T09:30:01+00:00"

The `+00:00` is Ruby's default behaviour so I would not want to change it; also I enabled it in [our grammar](https://github.com/inukshuk/edtf-ruby/blob/master/lib/edtf/parser.y#L55) specifically, that's why I believe it was probably part of a previous version of the EDTF BNF.

**Comment by inukshuk** [comment]
I should mention that I added a `skip_timezone` property similar to the other extended properties to keep track of this behaviour and to allow us to use it even without parsing a string first. Perhaps we could use a better name, though? 'Implicitly local' or something like that? (Though that is dangerous if Ruby treats such a string as implicitly UTC).

**Comment by no-reply** [comment]
This looks good. 

I have no problem with `+00:00` as a representation of `Z`.  It seems like a mistake in EDTF that it's disallowed, and possibly an issue that should be raised.  As long as we can accurately serialize "local" times through `#edtf`, I'm good.

:rocket:

**Comment by no-reply** [comment]
I should also say thanks for responsiveness and all your work on this.  Digital Public Library of America is using this gem heavily, and expects to be able to contribute to its maintenance.

**Comment by inukshuk** [comment]
That sounds great!

I already pushed the changes to RubyGems... though I'm not sold on the `skip_timezone` name like I said.
