### ISSUE TITLE
Reordering reversed intervals or do not accept them as valid intervals.

### ISSUE THREAD

**Issue by grosscol** [inukshuk/edtf-ruby#19]
I've come across the situation where I may end up with reversed intervals.  That is to say, the start date is greater than the end date.  I would expect the behavior of this to either automatically reverse the start and end, or throw an ArgumentError during construction.

Given a start that occurs after the end results in an Interval.  The interval just behaves badly.

``` ruby
space_oddessy = Date.edtf('2010/2001')
space_oddessy.begin # nil
space_oddessy.end # nil
space_oddessy.precision # NoMethodError: undefined method `precision' for nil:NilClass
```

I'm currently handling this at the application level with something like:

``` ruby
    # Determines if an intervals endings are reverse.  Specifically, where the begin 
    # date is later that the end date.  An interval with reversed starting and ending
    # dates will have from and to attributes, but begin and end will be nil
    # == Parameters:
    # interv::
    #   [EDTF::Interval] The interval to be tested. 
    # == Returns:
    #   [Boolean] True if the interval boundaries were reversed
    def self.interval_reversed?(interv)
      return false if interv.from == EDTF_BEGIN_OPEN || interv.to == EDTF_END_OPEN
      (interv.from && !interv.begin) && (interv.to && !interv.end)
    end

    # Reverse the begin and end of an interval.  This will bork a well formed interval.
    # == Parameters:
    # interv::
    #   [EDTF::Interval] The interval to be reversed. 
    # == Returns:
    #   [EDTF::Interval] A new interval with from and to in the reverse order from the input interval.
    def self.reverse_interval(interv)
      EDTF::Interval.new(interv.to, interv.from)
    end
```

Not sure what the behavior should be: do not accept reversed intervals or reorder reversed intervals.

**Comment by no-reply** [comment]
Note that the [specification (5.1.3)](http://www.loc.gov/standards/datetime/pre-submission.html#interval) disallows reversed intervals:

> The end endpoint must be later than or equal to the start endpoint.

I'm -1 on flipping them automatically; that would be both off-spec and surprising behavior.

@grosscol it seems like raising an error at parse time would leave you with fewer options to fix bad dates. Other than adding `#valid?` or similar, I'm not sure how to improve this.

**Comment by inukshuk** [comment]
Are there legitimate use cases for reversed intervals? In that case, the best solution would be ensure that interval objects behave nicely (and provide helpers like those above). Otherwise, I'd be in favor of disallowing reversed intervals completely, i.e., not parsing them and throwing ArgumentErrors when trying to create one (since we'll add checks to the interval setters anyway). The latter approach would be in line with the spec, obviously, but if reversed intervals can be useful I don't see why we should prohibit them. So I'm curious @grosscol -- in what situations do you end up with reversed intervals?
