### ISSUE TITLE
Precision of date in set, when attribute later is true

### ISSUE THREAD

**Issue by animosic** [inukshuk/edtf-ruby#26]
It seems that the precision of date in set is incorrect, when attribute later is true.

`irb(main):001:0> s = Date.edtf('[1984,1985-10-01..]')`
`=> #<EDTF::Set:0x007fe7709a3e90 @dates=#<Set: {Sun, 01 Jan 1984, Tue, 01 Oct 1985}>, @choice=true, @later=true, @earlier=false>`

`irb(main):002:0> s.entries.map { |date| date.precision }`
`=> [:year, :year]`

Expected values:
`=> [:year, :day]`

If attribute later is false, the parser works as expected:

`irb(main):003:0> s = Date.edtf('[1984,1985-10-01]')`
`=> #<EDTF::Set:0x007fe770b67c68 @dates=#<Set: {Sun, 01 Jan 1984, Tue, 01 Oct 1985}>, @choice=true, @later=false, @earlier=false>`

`irb(main):004:0> s.entries.map { |date| date.precision }`
`=> [:year, :day]`

**Comment by inukshuk** [comment]
Wow, good catch!

Just pushed out 3.0.3 to address this. Thanks for reporting!

**Comment by animosic** [comment]
Very good. Thank you!
