### ISSUE TITLE
Can't parse season intervals or the combination 'u?'

### ISSUE THREAD

**Issue by eltiffster** [inukshuk/edtf-ruby#33]

**Comment by eltiffster** [comment]
Sorry, pressed Enter by mistake

**Comment by inukshuk** [comment]
Thanks! Unspecified dates with month precision were simply missing in the grammar -- I added those.

I'm not sure that unspecified and uncertain years are valid? I just checked in edtf.js which already implements the newer, standardised version of the spec and it is not supported there either.

Season intervals are also tricky: in edtf.js we added support for them as part of an experimental level 3 -- but they are explicitly not covered by the specification. If/when we update edtf-ruby to use the same grammar as edtf.js it will also allow season interval, but they are definitely not part of the spec officially.

**Comment by eltiffster** [comment]
Thank you, @inukshuk!
